server:
  port: 8032
spring:
  application:
    name: hystrix-turbine-mq

  # rabbitmq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


