server:
  port: 8031
spring:
  application:
    name: hystrix-turbine

# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


turbine:
  cluster-name-expression: "'default'"
  app-config: consumer-movie-ribbon-hystrix,consumer-movie-feign-hystrix-fallback-stream #监控的微服务
