server:
  port: 8031
spring:
  application:
    name: hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

turbine:
  app-config-list: consumer-movie-ribbon-hystrix,consumer-movie-feign-hystrix-fallback-stream
  cluster-name-expression: "'default'"
