server:
  port: 8080
spring:
  application:
    name: provider-user
  datasource:
    url: jdbc:mysql://192.168.3.108:3306/microserver?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}