spring:
  application:
    name: gateway-zuul-file-upload
server:
  port: 8040

# eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #Eureka Server交互地址，查询服务和注册服务都需要依赖这个地址，多个用逗号分隔。
  instance:
    prefer-ip-address: true



management:
  security:
    enabled: false


zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
