server:
  port: 9080
spring:
  application:
    name: gateway-zuul

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: routes
zuul:
  routes:
    movie-ribbon:
      path: /api/ribbon/**
      serviceId: movie-ribbon
    movie-feign:
      path: /api/**
      serviceId: movie-feign
    local:
      path: /my/**
      url: forward:/
  AccessFilter:
    pre:
      disable: true