spring:
  application:
    name: gateway-zuul-reg-exp
server:
  port: 8041

# eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #Eureka Server交互地址，查询服务和注册服务都需要依赖这个地址，多个用逗号分隔。
  instance:
    prefer-ip-address: true

management:
  security:
    enabled: false

